export const categoryOrder = [
  'All components',
  'Actions',
  'Forms',
  'Layout',
  'Navigation',
  'Feedback',
  'Data',
  'Conversation',
] as const;

export const componentInfo: Record<string, { description: string; category: string }> = {
  'field-error': { description: 'Connect validation feedback to its form field.', category: 'Forms' },
  accordion: { description: 'Reveal related sections of content one panel at a time.', category: 'Layout' },
  'alert-dialog': { description: 'Ask for confirmation before an action that needs a deliberate decision.', category: 'Feedback' },
  alert: { description: 'Bring a message, warning, or update into the flow of a page.', category: 'Feedback' },
  'aspect-ratio': { description: 'Keep images and other media in a consistent proportion.', category: 'Layout' },
  attachment: { description: 'Present an attached file with its details and available actions.', category: 'Conversation' },
  avatar: { description: 'Represent people with an image, initials, or a fallback.', category: 'Data' },
  badge: { description: 'Give a status, category, or count a compact visual label.', category: 'Data' },
  breadcrumb: { description: 'Show the path to the current page and links back through it.', category: 'Navigation' },
  bubble: { description: 'Display a conversation bubble with content and optional reactions.', category: 'Conversation' },
  'button-group': { description: 'Connect related buttons into a single set of actions.', category: 'Actions' },
  button: { description: 'Trigger an action with a choice of emphasis and size.', category: 'Actions' },
  calendar: { description: 'Browse dates and choose a day from a calendar.', category: 'Forms' },
  callout: { description: 'Highlight a useful note or warning with a clear label.', category: 'Feedback' },
  card: { description: 'Arrange related content with a heading, body, and optional footer.', category: 'Layout' },
  carousel: { description: 'Move through a sequence of content panels.', category: 'Layout' },
  chart: { description: 'Present data visually with shared chart styling, tooltips, and legends.', category: 'Data' },
  checkbox: { description: 'Let people select independent options or confirm a choice.', category: 'Forms' },
  collapsible: { description: 'Expand or hide a section of content from a trigger.', category: 'Layout' },
  combobox: { description: 'Find and select an option from a searchable list.', category: 'Forms' },
  command: { description: 'Search a list of commands and choose an action with the keyboard.', category: 'Actions' },
  'context-menu': { description: 'Offer actions for an item through a contextual menu.', category: 'Actions' },
  'data-table': { description: 'Explore tabular data with sorting, filtering, selection, and pagination.', category: 'Data' },
  'date-picker': { description: 'Choose a date through a compact field and calendar.', category: 'Forms' },
  dialog: { description: 'Focus attention on a task or message in an overlay.', category: 'Layout' },
  direction: { description: 'Set the reading direction for components in a section.', category: 'Layout' },
  drawer: { description: 'Open supporting content in a panel from the edge of the screen.', category: 'Layout' },
  'dropdown-menu': { description: 'Reveal a compact menu of actions from a button.', category: 'Actions' },
  empty: { description: 'Explain an empty state and offer a useful next action.', category: 'Feedback' },
  field: { description: 'Compose a form control with its label, description, and error message.', category: 'Forms' },
  form: { description: 'Connect form controls to validation and helpful field messages.', category: 'Forms' },
  'group-label': { description: 'Introduce a group of content with a small, distinctive label.', category: 'Layout' },
  'hover-card': { description: 'Preview supporting information when a linked item is hovered or focused.', category: 'Feedback' },
  'input-group': { description: 'Combine a text field with icons, buttons, and supporting text.', category: 'Forms' },
  'input-otp': { description: 'Enter a short verification code in individually spaced slots.', category: 'Forms' },
  input: { description: 'Collect a single line of text with clear focus and disabled states.', category: 'Forms' },
  item: { description: 'Build a content row with media, details, and actions.', category: 'Layout' },
  kbd: { description: 'Show a keyboard key or shortcut alongside an action.', category: 'Data' },
  label: { description: 'Give a form control a readable, connected label.', category: 'Forms' },
  marker: { description: 'Highlight text or mark a section with a label and optional icon.', category: 'Conversation' },
  menubar: { description: 'Arrange application commands in a horizontal row of menus.', category: 'Navigation' },
  'message-scroller': { description: 'Keep a scrolling conversation easy to follow as messages arrive.', category: 'Conversation' },
  message: { description: 'Compose a message with an avatar, heading, content, and actions.', category: 'Conversation' },
  'native-select': { description: 'Choose an option with the browser’s familiar select control.', category: 'Forms' },
  'navigation-menu': { description: 'Organize site links in a navigation menu with optional content panels.', category: 'Navigation' },
  pagination: { description: 'Move between pages of a longer list or collection.', category: 'Navigation' },
  popover: { description: 'Place a small interactive panel beside its trigger.', category: 'Layout' },
  progress: { description: 'Show how far a task has advanced toward completion.', category: 'Feedback' },
  questionnaire: { description: 'Guide people through questions, choices, and steps toward a submission.', category: 'Forms' },
  'radio-group': { description: 'Let people choose one option from a related set.', category: 'Forms' },
  resizable: { description: 'Let people adjust the space shared by adjacent panels.', category: 'Layout' },
  'scroll-area': { description: 'Contain overflowing content in a styled scrolling region.', category: 'Layout' },
  'search-field': { description: 'Open a search or command launcher from a prominent field-shaped button.', category: 'Actions' },
  select: { description: 'Choose one option from a styled dropdown list.', category: 'Forms' },
  separator: { description: 'Divide neighboring content with a horizontal or vertical rule.', category: 'Layout' },
  sheet: { description: 'Show related content or controls in a side panel.', category: 'Layout' },
  sidebar: { description: 'Build an application sidebar with grouped links and collapsible sections.', category: 'Navigation' },
  skeleton: { description: 'Show the shape of content while it is loading.', category: 'Feedback' },
  slider: { description: 'Adjust a value or range along a track.', category: 'Forms' },
  sonner: { description: 'Display brief notifications through the Sonner toast system.', category: 'Feedback' },
  spinner: { description: 'Indicate that an action or piece of content is loading.', category: 'Feedback' },
  switch: { description: 'Turn a setting on or off with a two-state control.', category: 'Forms' },
  table: { description: 'Display structured information in rows and columns.', category: 'Data' },
  tabs: { description: 'Switch between related views within the same space.', category: 'Navigation' },
  textarea: { description: 'Collect longer text in a multiline field.', category: 'Forms' },
  toast: { description: 'Present a brief notification with optional action and dismissal.', category: 'Feedback' },
  toaster: { description: 'Place and manage the library’s toast notifications.', category: 'Feedback' },
  'toggle-group': { description: 'Group toggle buttons for choosing one or several settings.', category: 'Actions' },
  toggle: { description: 'Turn a button’s active state on or off.', category: 'Actions' },
  'tool-row': { description: 'Present a tool or resource with an icon, details, and an action.', category: 'Data' },
  tooltip: { description: 'Explain a control with a brief message on hover or focus.', category: 'Feedback' },
  'top-nav': { description: 'Compose a top navigation bar with branding, links, and actions.', category: 'Navigation' },
  typography: { description: 'Set headings, paragraphs, lists, and supporting text in a consistent rhythm.', category: 'Layout' },
  fields: { description: 'See native form fields composed with labels and supporting text.', category: 'Forms' },
  conversation: { description: 'See message, bubble, and attachment pieces composed into a conversation.', category: 'Conversation' },
};
