// Generated by scripts/build-swift-tokens.mjs from src/styles/styles.css.
// Edit the shared theme, then regenerate.

/// Shared EnoughUI RGB values, available without a view or an appearance.
public enum EnoughPalette {
    public static let ink: UInt32 = 0x12151C
    public static let inkSecondary: UInt32 = 0x1C202B
    public static let paper: UInt32 = 0xF4F5F8
    public static let card: UInt32 = 0xFAFBFC
    public static let surface: UInt32 = 0xFFFFFF
    public static let hairline: UInt32 = 0xDDE1E8
    public static let hairlineSoft: UInt32 = 0xEEF0F4
    public static let border: UInt32 = 0xC6CCD6
    public static let text: UInt32 = 0x12151C
    public static let secondaryText: UInt32 = 0x3D4553
    public static let muted: UInt32 = 0x626B7A
    public static let hint: UInt32 = 0x5E6778
    public static let darkText: UInt32 = 0xFAFBFC
    public static let darkSecondaryText: UInt32 = 0xD5DAE2
    public static let darkMuted: UInt32 = 0x9AA3B2
    public static let accent: UInt32 = 0x3B4FE4
    public static let accentSoft: UInt32 = 0xEEF0FB
    public static let darkAccent: UInt32 = 0x7D89F0
    public static let success: UInt32 = 0x1A7F37
    public static let darkSuccess: UInt32 = 0x6FBF87
    public static let warning: UInt32 = 0x8A6508
}
